services:
  web:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure
    volumes:
      - .:/app
    command: gunicorn app.main:app --bind 0.0.0.0:5050 --workers 4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  db:
    image: mysql:8.4.5
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  db_data:
    driver: local